FROM python:3.12.7-slim

# coping all files to docker image
WORKDIR /app
COPY . /app

# updating linux system
RUN apt-get update
RUN apt-get upgrade -y

# installing java
RUN apt-get install openjdk-17-jdk -y --fix-missing
RUN apt-get install openjdk-17-jre -y
RUN apt-get install ant -y
RUN apt-get install ca-certificates-java -y

# fix certificates
RUN update-ca-certificates -f

# exporting environment vars
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64
ENV JAVA_HOME_BIN /usr/lib/jvm/java-17-openjdk-amd64/bin

RUN export JAVA_HOME
RUN export PATH=$PATH:JAVA_HOME_BIN

# clean installation
RUN apt-get clean

# install python on image
RUN pip3 install -r /app/requirements.txt

# install playwright dependencies
RUN playwright install-deps
RUN playwright install
RUN apt-get install libgbm1
RUN apt-get install libxkbcommon0

# Google credentials
ARG GOOGLE_PASSWORD
ENV GOOGLE_PASSWORD=${GOOGLE_PASSWORD}

ARG GOOGLE_EMAIL
ENV GOOGLE_EMAIL=${GOOGLE_EMAIL}

# Support credentials
ARG SUPPORT_PASSWORD
ENV SUPPORT_PASSWORD=${SUPPORT_PASSWORD}

ARG SUPPORT_EMAIL
ENV SUPPORT_EMAIL=${SUPPORT_EMAIL}

# Firebase credentials
ARG AUTH_FIREBASE_PROJECT_ID
ENV AUTH_FIREBASE_PROJECT_ID=${AUTH_FIREBASE_PROJECT_ID}

ARG AUTH_FIREBASE_CLIENT_EMAIL
ENV AUTH_FIREBASE_CLIENT_EMAIL=${AUTH_FIREBASE_CLIENT_EMAIL}

ARG AUTH_FIREBASE_PRIVATE_KEY
ENV AUTH_FIREBASE_PRIVATE_KEY=${AUTH_FIREBASE_PRIVATE_KEY}

ARG FIREBASE_CLIENT_ID
ENV FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}

ARG FIREBASE_AUTH_URI
ENV FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}

ARG FIREBASE_TOKEN_URI
ENV FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}

ARG FIREBASE_CERT_URL
ENV FIREBASE_CERT_URL=${FIREBASE_CERT_URL}

ARG FIREBASE_CERT_CLIENT_URL
ENV FIREBASE_CERT_CLIENT_URL=${FIREBASE_CERT_CLIENT_URL}

ARG FIREBASE_UNIVERSE_DOMAIN
ENV FIREBASE_UNIVERSE_DOMAIN=${FIREBASE_UNIVERSE_DOMAIN}

ARG FIREBASE_API_KEY
ENV FIREBASE_API_KEY=${FIREBASE_API_KEY}

ARG FIREBASE_AUTH_DOMAIN
ENV FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}

ARG FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}

ARG FIREBASE_STORAGE_BUCKET
ENV FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}

ARG FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}

ARG FIREBASE_APP_ID
ENV FIREBASE_APP_ID=${FIREBASE_APP_ID}

ARG FIREBASE_MEASUREMENT_ID
ENV FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}

ARG FIREBASE_PRIVATE_KEY_ID
ENV FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}

# Application-specific
ARG INSPETOR_URL
ENV INSPETOR_URL=${INSPETOR_URL}

CMD ["python3", "main.py"]